# multiply - global
# left - local
# right - local
# get_num - global
# prompt - local
# input - built-in
# float - built-in
# first_number - global
# second_number - global
# product - global
# print - built-in